-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 11:25:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema comercio_venda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comercio_venda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comercio_venda` DEFAULT CHARACTER SET utf8 ;
USE `comercio_venda` ;

-- -----------------------------------------------------
-- Table `comercio_venda`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercio_venda`.`produto` (
  `id_produto` INT NOT NULL,
  `nome_produto` VARCHAR(100) NOT NULL,
  `quantidade_stock_produto` INT NOT NULL,
  `preco_produto` DECIMAL(10,3) NOT NULL,
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC) VISIBLE,
  PRIMARY KEY (`nome_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comercio_venda`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercio_venda`.`vendedor` (
  `id_vendedor` INT NOT NULL,
  `nome_vendedor` VARCHAR(100) NOT NULL,
  `salario_vendedor` DECIMAL(10,3) NOT NULL,
  UNIQUE INDEX `id_vendedor_UNIQUE` (`id_vendedor` ASC) VISIBLE,
  PRIMARY KEY (`nome_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comercio_venda`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercio_venda`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `nome_produto_venda` VARCHAR(100) NOT NULL,
  `preco_produto_venda` DECIMAL(10,3) NOT NULL,
  `quantidade_produto_venda` INT NOT NULL,
  `total_venda` DECIMAL(10,3) NOT NULL,
  `nome_vendedor_venda` VARCHAR(100) NOT NULL,
  `data_venda` DATETIME NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_produto_idx` (`nome_produto_venda` ASC) VISIBLE,
  INDEX `fk_venda_vendedor1_idx` (`nome_vendedor_venda` ASC) VISIBLE,
  CONSTRAINT `fk_venda_produto`
    FOREIGN KEY (`nome_produto_venda`)
    REFERENCES `comercio_venda`.`produto` (`nome_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_vendedor1`
    FOREIGN KEY (`nome_vendedor_venda`)
    REFERENCES `comercio_venda`.`vendedor` (`nome_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
