-- MySQL Script generated by MySQL Workbench
-- Fri Jan 26 00:18:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empreendimento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empreendimento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empreendimento` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `empreendimento` ;

-- -----------------------------------------------------
-- Table `empreendimento`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empreendimento`.`venda` (
  `id_venda_venda` INT NOT NULL AUTO_INCREMENT,
  `nome_produto_venda` VARCHAR(100) NOT NULL,
  `quantidade_produto_venda` INT NOT NULL,
  `preco_produto_venda` DOUBLE NOT NULL,
  `total_valor_venda_venda` DOUBLE NOT NULL,
  `nome_vendedor_venda` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_venda_venda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empreendimento`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empreendimento`.`produto` (
  `id_produto_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto_produto` VARCHAR(100) NOT NULL,
  `quantidade_estock_produto_` INT NOT NULL,
  `preco_produto_produto` DOUBLE NOT NULL,
  PRIMARY KEY (`id_produto_produto`),
  INDEX `fk_produto_venda_idx` (`nome_produto_produto` ASC) VISIBLE,
  INDEX `fk_produto_venda1_idx` (`preco_produto_produto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_venda`
    FOREIGN KEY (`nome_produto_produto`)
    REFERENCES `empreendimento`.`venda` (`nome_produto_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_venda1`
    FOREIGN KEY (`preco_produto_produto`)
    REFERENCES `empreendimento`.`venda` (`preco_produto_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
