-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 17:47:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema automoveis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema automoveis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `automoveis` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `automoveis` ;

-- -----------------------------------------------------
-- Table `automoveis`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automoveis`.`carro` (
  `id_carro` INT NOT NULL,
  `numero_matricula_carro` VARCHAR(50) NOT NULL,
  `marca_carro` VARCHAR(50) NOT NULL,
  `modelo_carro` VARCHAR(50) NOT NULL,
  `preco_carro` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`numero_matricula_carro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `automoveis`.`venda_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automoveis`.`venda_carro` (
  `id_venda_carro` INT NOT NULL AUTO_INCREMENT,
  `marca_venda_carro` VARCHAR(50) NOT NULL,
  `modelo_venda_carro` VARCHAR(50) NOT NULL,
  `cor_venda_carro` VARCHAR(30) NULL DEFAULT NULL,
  `numero_matricula_venda_carro` VARCHAR(50) NOT NULL,
  `preco_venda_carro` FLOAT NOT NULL,
  `data_venda_carro` DATE NOT NULL,
  `carro_numero_matricula_carro` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_venda_carro`, `carro_numero_matricula_carro`),
  INDEX `IDX_marca_carro` (`marca_venda_carro` ASC) VISIBLE,
  INDEX `fk_venda_carro_carro_idx` (`carro_numero_matricula_carro` ASC) VISIBLE,
  CONSTRAINT `fk_venda_carro_carro`
    FOREIGN KEY (`carro_numero_matricula_carro`)
    REFERENCES `automoveis`.`carro` (`numero_matricula_carro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
